version: '3'

services:
  body_progress_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=bestrong
      - DB_USERNAME=${MONGODB_USERNAME}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=https://${AUTH0_DOMAIN}/
    networks:
      - bestrong

  body_progress_front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_APP_PORT=3000
      - VITE_API_URL=http://body_progress_api:3001
      - VITE_AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - VITE_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - VITE_AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    networks:
      - bestrong
  
  mongo:
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_DB_NAME=bestrong
      - MONGO_DB_USERNAME=${MONGODB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
    networks:
      - bestrong

networks:
  bestrong:
    driver: bridge

volumes:
  MONGO_DATA:
    name: mongo_data
  MONGO_CONFIG:
    name: mongo_config